Set the stagingRepositoryId for the io.codearte.nexus-staging plugin
marcphilipp/nexus-publish-plugin pull request #16
Opened 2019-01-08 01:00 UTC by Vampire

Closes #11

2019-01-08 10:30 UTC, szpak commented on src/main/java/de/marcphilipp/gradle/nexus/InitializeNexusStagingRepository.java
> +                                        // just ignore, the fallback logic will find the repository id automatically
I would display some warning here anyway. As you check the types using in that method it shouldn't rather fail under normal circumstances. A warning message should suggest user that there is something wrong, a release reliability is affected and it's probably good to report it as an issue to explain.

2019-01-08 10:36 UTC, szpak commented on src/main/java/de/marcphilipp/gradle/nexus/InitializeNexusStagingRepository.java
> +                                .ifPresent(method -> {
It doesn't fit greatly in the logic supported by `Optional`, but due to limited reliability if user has applied "io.codearte.nexus-staging" and that method is not available he or she should be aware than upgrading to 0.20.0+ is recommended. Therefore, I would display a corresponding warning here.

2019-01-08 11:13 UTC, szpak commented
@Vampire You can also bump the "io.codearte.nexus-staging" dependency in the project to 0.20.0.

2019-01-08 12:54 UTC, Vampire commented on src/main/java/de/marcphilipp/gradle/nexus/InitializeNexusStagingRepository.java
> +                                .ifPresent(method -> {
you are probably right, fixed

2019-01-08 12:54 UTC, Vampire commented on src/main/java/de/marcphilipp/gradle/nexus/InitializeNexusStagingRepository.java
> +                                        // just ignore, the fallback logic will find the repository id automatically
you are probably right, fixed

2019-01-08 12:55 UTC, Vampire commented on src/main/java/de/marcphilipp/gradle/nexus/InitializeNexusStagingRepository.java
> +                                .ifPresent(method -> {
Nah, fits great.
Would fit better with `ifPresentOrElse` in Java 9, but `isPresent` is also ok.
Fixed.

2019-01-08 15:42 UTC, szpak approved these changes

2019-01-08 15:43 UTC, szpak approved these changes
LGTM (looking at the functionality provided :) ).

2019-01-08 19:13 UTC, marcphilipp commented on src/main/java/de/marcphilipp/gradle/nexus/InitializeNexusStagingRepository.java
> +                        java.util.Optional<Method> getStagingRepositoryId = Arrays
Could we call the method and catch a `NoSuchMethodError` instead?

2019-01-08 19:14 UTC, Vampire commented on src/main/java/de/marcphilipp/gradle/nexus/InitializeNexusStagingRepository.java
> +                        java.util.Optional<Method> getStagingRepositoryId = Arrays
We can if you prefer. I try to avoid exceptions for flow-control where I can, but it is your code-base. :-)

2019-01-08 19:16 UTC, Vampire commented on src/main/java/de/marcphilipp/gradle/nexus/InitializeNexusStagingRepository.java
> +                        java.util.Optional<Method> getStagingRepositoryId = Arrays
Oh, you mean really compiling against it?
I first thought getting the method by name via reflection and catching the no such method error.

2019-01-08 20:25 UTC, Vampire commented on src/main/java/de/marcphilipp/gradle/nexus/InitializeNexusStagingRepository.java
> +                        java.util.Optional<Method> getStagingRepositoryId = Arrays
In my original PR I didn't update the dependency version, so that didn't work, didn't actually think about it though. :-D
Fixed now.

2019-01-08 20:40 UTC, szpak commented on src/main/java/de/marcphilipp/gradle/nexus/InitializeNexusStagingRepository.java
> +                        java.util.Optional<Method> getStagingRepositoryId = Arrays
It's good to read the original issue #11 :)

> Regarding reflection concerns I propose to put the newer GNSP version as compileOnly/provided dependency and call the stagingRepositoryId getter in a try..catch block. On NoSuchMethodError (or something) you could just display warning than upgrading GNSP to the newer version (probably named 0.20.0) would improve releasing reliability.

2019-01-08 23:01 UTC, Vampire commented on src/main/java/de/marcphilipp/gradle/nexus/InitializeNexusStagingRepository.java
> +                                        // just ignore, the fallback logic will find the repository id automatically
Hm, I did, but I overlooked that one obviously.

2019-01-08 23:03 UTC, Vampire commented on src/main/java/de/marcphilipp/gradle/nexus/InitializeNexusStagingRepository.java
> +                        java.util.Optional<Method> getStagingRepositoryId = Arrays
Hm, I did, but I overlooked that one obviously.

2019-01-14 18:45 UTC, marcphilipp requested changes
@Vampire Thanks! Could you please add an integration test or shall I take it from here?

2019-01-22 22:03 UTC, szpak commented
@Vampire Do you need any assistance with Gradle TestKit?

2019-01-27 15:28 UTC, marcphilipp commented
@Vampire friendly ping! 🙂

2019-01-28 02:13 UTC, Vampire commented
Sorry, I was distracted by other projects.
I tried to add a test, but I fail to do so with `Caused by: java.lang.ClassNotFoundException: io.codearte.gradle.nexus.NexusStagingExtension` which I find rather strange, as obviously the plugin is applied, or it wouldn't even get to the point where it fails.

2019-01-28 09:01 UTC, szpak commented
@Vampire Do you have my plugin added to the buildscript section in your TestKit project as a dependency? It's `compileOnly` in nexus-publish-plugin and it may not be pulled automatically in your test execution.

2019-01-28 09:09 UTC, Vampire commented
I tried with
```gradle
plugins {
    id('java-library')
    id('io.codearte.nexus-staging') version '0.20.0'
    id('de.marcphilipp.nexus-publish')
}
```
and
```gradle
buildscript {
    repositories {
        gradlePluginPortal()
    }
    dependencies {
        classpath "io.codearte.gradle.nexus:gradle-nexus-staging-plugin:0.20.0"
    }
}
plugins {
    id('java-library')
    id('io.codearte.nexus-staging') version '0.20.0'
    id('de.marcphilipp.nexus-publish')
}
```
both times the same error.

2019-01-28 09:09 UTC, Vampire commented
Actually I have a test now that runs without testkit but lower level, but I still wonder why it wont work.

2019-01-28 09:17 UTC, szpak commented
Hmm, I would expect the second variant to work. I don't why it doesn't.

2019-01-28 09:35 UTC, Vampire commented
You're welcome to have a look @szpak, I pushed the current state as WIP commit.
I wouldn't have expected any difference actually, the `id('io.codearte.nexus-staging') version '0.20.0'` should already add the plugin to the classpath I think.

2019-01-28 09:39 UTC, szpak commented
I forgot you use the `plugins {}` section. The dependency in my case was required as I was using the syntax with 'apply plugin: ...`.

2019-01-29 02:32 UTC, Vampire commented
Ok, now I got it managed.
Ready for re-review @marcphilipp :-)

2019-01-29 08:44 UTC, Vampire commented
I added another test that verifies the warning

2019-01-29 09:08 UTC, szpak commented
:+1: 

@marcphilipp Is it a known limitation of TestKit to do no support `plugins { id('io.codearte.nexus-staging') version '0.20.0' }` for external plugins (just the good old `buildscript` with `apply plugin:`)?

2019-02-02 09:20 UTC, marcphilipp commented
> Is it a known limitation of TestKit to do no support `plugins { id('io.codearte.nexus-staging') version '0.20.0' }` for external plugins (just the good old `buildscript` with `apply plugin:`)?

Not as far as I know. I'll look into it.

2019-02-02 09:22 UTC, marcphilipp approved these changes
Awesome! 👍

2019-02-02 09:23 UTC, merged