Make publishToNexus depend only on publish tasks with the correct repository
marcphilipp/nexus-publish-plugin pull request #20
Opened 2019-01-10 11:03 UTC by Vampire

2019-01-12 12:20 UTC, marcphilipp requested changes
Looks good, but I think we should learn from my mistakes and add an integration test.

@Vampire Could you please add one?

2019-01-29 11:42 UTC, Vampire commented
Definitely, test is added

2019-01-31 20:14 UTC, marcphilipp approved these changes

2019-01-31 20:16 UTC, merged

2019-01-31 20:16 UTC, marcphilipp commented
Thanks, @Vampire! 👍